### ISSUE TITLE
Возможная ошибка в команде из README.md

### ISSUE THREAD

**Issue by Unknown-Negotiator** [MNV/python-course-bibliography-generator#5]
В "README.md" файле в разделе "Usage" в 5 пукте в тексте команды в качестве --path_output аргумента указан эксель-файл /media/output.xlsx, хотя должен быть .docx файл.

**Comment by MNV** [comment]
> В "README.md" файле в разделе "Usage" в 5 пукте в тексте команды в качестве --path_output аргумента указан эксель-файл /media/output.xlsx, хотя должен быть .docx файл.

Да, действительно. Спасибо!
